### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by ciprianflorescu** [ihodev/sublime-boxy#150]
Did you even check if your package dependencies are actually available to install manually or did you not?

Trying to get pygments for example, but the archive from their site gives errors why I try to unarchive it.

https://pypi.python.org/pypi/Pygments

None of their repo paths works with Sublime: 

https://github.com/stutrek/Sublime-Text-3-Settings/tree/master/Packages/pygments
https://github.com/stutrek/Sublime-Text-3-Settings/tree/master/Packages/pygments/all/pygments

**Comment by ciprianflorescu** [comment]
First, I tried to install the theme using the ST3 package installer, but there's no Boxy Theme package there.

**Comment by ihodev** [comment]
@ciprianflorescu Ah, sorry, I was AFK. Do you resolve your issue?
