### ISSUE TITLE
Question: what theme scope sets the background color of the sidebar?

### ISSUE THREAD

**Issue by JeNeSuisPasDave** [ihodev/sublime-boxy#152]
For my dark themes, I don't want the background to be some light shade. I need higher contrast so I always set the background to black or something very very close to black.

In any of the dark Boxy themes, how do I set the background color of the sidebar to something other than the default? Specifically, suppose i want to set it to #000000FF ... how would I change the tmTheme file to accomplish that? And which tmTheme file would I change?

**Comment by ihodev** [comment]
`tmTheme` affects only color schemes, for customizing sidebar you have to update `*.sublime-theme`.
