### ISSUE TITLE
[tabs]: standard, but flat.

### ISSUE THREAD

**Issue by math2001** [ihodev/sublime-boxy#154]
Hi!

I *love* your theme, but just today, I saw this one: [Minimist](https://github.com/worg/Minimist-SublimeTheme), and the tabs are just awesome. So, I was wondering if there could be those same flat-standard tabs on boxy.

I saw the `theme_tab_rounded` options, but it's not what I expected...

I looked at the code to add it myself and... well first: **You're amazing! You've done so much!**. I try to edit, but themes aren't my thing at all. Here's what I get:

![Just ok](https://cloud.githubusercontent.com/assets/15224242/21558592/bf27a55e-ce90-11e6-9ab6-4a79f888fc8c.png)

*I don't know why but the cursor's gone, so, with my artistic talent, I drew my own* :laughing:

So, it's only working the `Boxy yesterday`, it's too spread, and when it's not hovered/selected, there is no shape. But it's suppose to look like on *minimist*. What do you think? Does it looks good to you? To much work (or it's just me that didn't understood how it worked at all)?

Thanks again for Boxy, *c'est genial*!

Matt

**Comment by ihodev** [comment]
Hi, Matt! I'm agree with you, standard tabs looks great, I'll add them for all themes in the next release :wink:

**Comment by math2001** [comment]
Awesome!! Can't wait for the next release then!

![super excited  gif](http://www.reactiongifs.com/wp-content/uploads/2012/05/excited4.gif)

**Comment by ihodev** [comment]
Hi, @math2001. After some investigation, I've found that this is not so simple task with current approach (requires too many override styles). I have plans to create Boxy's successor theme with better settings management and hackability, however I have no any ETA, but sure I'll add standard flat variant of the tabs.
