### ISSUE TITLE
Option for Find Panel input field font size

### ISSUE THREAD

**Issue by djmtype** [ihodev/sublime-boxy#155]
While there's an option to change the Find Panel font size, this only applies to the buttons, but not the input field next to it. 

Including `"theme_find_panel_size_xl": true` option in the screenshot for example.
https://cloudup.com/cvdHFJvC6rb

**Comment by michaelblyons** [comment]
Duplicate of #48?

**Comment by djmtype** [comment]
Yep. Duplicate issue.
