### ISSUE TITLE
Assets generation based on color

### ISSUE THREAD

**Issue by johannes-z** [ihodev/sublime-boxy#156]
I added my own theme and color theme, and need to update all the assets to represent the main colors. Do I have to do that by hand or is there a script or something?

**Comment by ihodev** [comment]
> Do I have to do that by hand or is there a script or something?
@johannes-z Hi! Unfortunately you have to do that by your hand :(

**Comment by johannes-z** [comment]
We could use GIMP's CLI and the `Color Exchange` filter (which is what I used by doing it manually). I 
will look into this...
