### ISSUE TITLE
Design problem - Text position

### ISSUE THREAD

**Issue by jhaemin** [ihodev/sublime-boxy#157]
1. Sidebar file icon position is little bit higher.
![screenshot 17](https://cloud.githubusercontent.com/assets/19797697/21705942/9137040c-d406-11e6-988e-e48f6a7400d7.png)
Items are not vertically middle.

2. Finding text position is little bit higher.
![screenshot 18](https://cloud.githubusercontent.com/assets/19797697/21705964/b4774922-d406-11e6-89d8-683d4417cf29.png)
Again, text must go downside a little bit.

**Comment by ihodev** [comment]
Unfortunately it's ST related issue. A position of the text depends on your OS and editor font, you can play with margins manually, however I didn't find better proportions.
