### ISSUE TITLE
Find panel replace line cut off by status bar

### ISSUE THREAD

**Issue by alecsatin** [ihodev/sublime-boxy#158]
First off, compliments for boxy.  Elegant.  Beautiful.  A real asset for Sublime.

The situation I'm having is that the replace line of the Find panel is being partially obstructed by the status bar.  [Screenshot](https://alecsatin.github.io/assets/ref-only/boxy-status-bar-cutting-off-replace-box.png)

There is probably a simple configuration fix which has eluded me.  The larger font on the status bar makes it much easier to see on this laptop display.

The settings from Preferences.sublime-settings - User are below.

Thanks for any help you might be able to provide.

```
	"theme": "Boxy Yesterday.sublime-theme",
	"theme_accent_mono": true,
	"theme_bar": true,
	"theme_find_panel_close_hidden": true,
	"theme_find_panel_font_xs": true,
	"theme_find_panel_padding_sm": true,
	"theme_find_panel_padding_xs": true,
	"theme_find_panel_size_xxs": true,
	"theme_font_md": true,
	"theme_icons_atomized": true,
	"theme_scrollbar_rounded": true,
	"theme_sidebar_heading_bold": true,
	"theme_sidebar_highlight_selected_text_only": true,
	"theme_sidebar_icon_saturation_lw": true,
	"theme_sidebar_indent_xs": true,
	"theme_sidebar_size_xxs": true,
	"theme_size_xs": true,
	"theme_statusbar_font_xl": true,
	"theme_tab_close_always_visible": true,
	"theme_tab_font_lg": true,
	"theme_tab_line_size_sm": true,
	"theme_tab_mouse_wheel_switch": true,
	"theme_tab_rounded": true,
	"theme_tab_selected_filled": true,
	"theme_tab_separator": true,
	"theme_tab_size_sm": true,
	"theme_tab_width_auto": true,
	"theme_tooltips_font_xl": true,
```
#### Your Environment
- Boxy Theme: 5.2.0
- Sublime Text: 3126
- Platform: linux
- Package Control: True
- Dependencies:
    * mdpopups: 1.13.1
    * markdown: 2.6.6
    * pygments: 2.1a0
    * jinja2: 2.8

**Comment by michaelblyons** [comment]
Is this the thing where if you drag the Find/Replace bar size up and back down, it becomes fixed?

**Comment by alecsatin** [comment]
Yes!  It's working now and keeping so after restarting Sublime Text.  So this is solved.
Thank you.

**Comment by ihodev** [comment]
@alecsatin Yes, that's known issue: https://github.com/ihodev/sublime-boxy/wiki#known-issues
