### ISSUE TITLE
Request: Settings for customizing the input panel

### ISSUE THREAD

**Issue by mattst** [ihodev/sublime-boxy#162]
I have just tried to use Boxy to customize the size and font size of the input panel and discovered that Boxy surprisingly has no settings for this. Any chance settings could be added for the input panel?

Thanks. :)

**Comment by ihodev** [comment]
@mattst Hello :wink: As far as I know you can't set different size options for input panel and find panel, the same story with the font size. However you can change font size via [Boxy Theme Addon - Widget Font Size](https://github.com/ihodev/sublime-boxy-addon-widget-font-size).

**Comment by mattst** [comment]
Thanks ihodev. 

That sets the font size of the input panel but not the font size of its label - can the label's font size be changed somehow?

**Comment by ihodev** [comment]
Hmm, I'll investigate this asap :wink:
