### ISSUE TITLE
Donating - too much hassle, what's wrong with PayPal

### ISSUE THREAD

**Issue by mattst** [ihodev/sublime-boxy#163]
I would like to donate BUT...

"Buy me a coffee/beer" style donations to open source projects should be easy to do so that those who wish to do so can do it with a few clicks. I think your choice of using [Patreon](https://www.patreon.com/ihodev) is **not serving your own financial interest**. It requires a monthly donation to be made on a site that most of your users won't know and will have the inconvenience of joining just to donate to you, furthermore most people who want to donate to an open source project won't want to set up a monthly donation or give their card details to a site that they've never heard of and have no reason to trust.

Why not add the ability for users to donate using PayPal - the vast majority of your users will already have a PayPal account and would be able to donate by entering the amount and 2 or 3 mouse clicks later, 20 seconds, and they're done - most importantly they know it will only take 20 seconds and that it is safe.

Just trying to be helpful...

**Comment by ihodev** [comment]
I'm fully agree with you. However I can't accept donations via PayPal, because it doesn't support receiving money in Ukraine. 

![PayPal - Ukraine](http://i.imgur.com/R9rqQMP.png)

The only possible options are Bitcoins and [Payoneer](https://www.payoneer.com/ru/). I've found that only Patreon supports Payoneer, that's why I choose it.

**Comment by equinusocio** [comment]
@ihodev Check also beerpay.

**Comment by mattst** [comment]
@ihodev 

Take a look at this [PayPal thread](https://www.paypal-community.com/t5/Selling-on-eBay/Paying-a-Seller-Based-in-The-Ukraine/td-p/805324?profile.language=en-gb) there is no sign of a resolution to the problem but page 3 has some interesting looking information. HTH.

**Comment by ihodev** [comment]
This is not relevant anymore. The theme will be deprecated in the near future.
