### ISSUE TITLE
Find Panel font too small

### ISSUE THREAD

**Issue by ooJerryLeeoo** [ihodev/sublime-boxy#164]
![screen shot 2017-03-18 at 21 40 08](https://cloud.githubusercontent.com/assets/20783502/24072533/870a5a60-0c23-11e7-91ee-4f44aa94f5c3.png)

**Comment by ihodev** [comment]
You can change it via [Boxy Theme Addon - Widget Font Size](https://packagecontrol.io/packages/Boxy%20Theme%20Addon%20-%20Widget%20Font%20Size)

**Comment by ooJerryLeeoo** [comment]
Thanks!!
