### ISSUE TITLE
[Enhancement] Seti_UI tabs style.

### ISSUE THREAD

**Issue by ooJerryLeeoo** [ihodev/sublime-boxy#165]
Is possible to add `Seti_UI` tabs style ?

![image](https://cloud.githubusercontent.com/assets/20783502/24297595/48e695ea-10de-11e7-8dfe-d8b7cadc8d4d.png)

**Comment by ihodev** [comment]
@ooJerryLeeoo Hello :wink: Please see #154.

**Comment by ooJerryLeeoo** [comment]
Oh, I totally didn't see that. Sorry 😜

**Comment by ooJerryLeeoo** [comment]
Should I close this issue?

**Comment by ihodev** [comment]
I think we can leave it. I know many users like "classic" variation of the ST tabs. I'll be back when I'll have some good news :wink:

**Comment by ooJerryLeeoo** [comment]
Ok, got it.

**Comment by ooJerryLeeoo** [comment]
Get any idea? I think this is easy for you, right?

**Comment by ooJerryLeeoo** [comment]
@ihodev I think you should tag this issue as `enhancement` not `question`.

**Comment by ihodev** [comment]
@ooJerryLeeoo Please, see [this comment](https://github.com/ihodev/sublime-boxy/issues/154#issuecomment-276052691). Currently I don't have plans to add this tab variant, but I hope I'll provide a new theme in the near future with better settings management system.

**Comment by ooJerryLeeoo** [comment]
Okay, I apologize for rushing you 😜

**Comment by gj1118** [comment]
Can we get a sneak peak of the new theme you said you are working on ? 🤓

**Comment by ihodev** [comment]
@gj1118 Sure :wink: Next shots show some stuff you've requested in #166: 

![da_ui_and_ayu_light](https://user-images.githubusercontent.com/9801624/28373356-c92c4fba-6caa-11e7-9c03-e021abbc2421.png "Da UI Theme & Ayu Light Color Scheme")
![da_ui_and_monokai_pro](https://user-images.githubusercontent.com/9801624/28373357-c92eca24-6caa-11e7-9349-602695af39e8.png "Da UI Theme & Monokai Pro Color Scheme")

I hope you'll see the first beta in a month :tada:

**Comment by gj1118** [comment]
Super awesome.. :) Thank you Sir!!!

**Comment by gj1118** [comment]
when will it be released ?  :)

**Comment by ihodev** [comment]
@gj1118 Sorry, I was too optimistic :disappointed:  I'm still working on it. Hopefully soon, however I can't say the exact date, don't want to disappointment you with another fake date.

**Comment by ihodev** [comment]
Latest news:

>  I wasn't expecting to see a new stable ST so early. I hope you'll see the first beta of the new theme on Monday / Tuesday. Then I'll start working on the new release of A File Icon.

**Comment by gj1118** [comment]
Awesome.. thank you sir.
Much appreciated..

:)

---------------------------
With Regards
Gagan Janjua

**Comment by ihodev** [comment]
Ok, 

https://github.com/ihodev/sublime-da-ui


Currently, can't setup installation via channel, so better to wait https://github.com/wbond/package_control_channel/pull/6611.

You can install it manually, extract `[DAUI.sublime-package](https://github.com/ihodev/sublime-da-ui/releases/download/v1.0.0-beta.1/DAUI.sublime-package)` to `Packages/DA UI`.

**Comment by gj1118** [comment]
I extracted the package to the packages folder. The options present
themselves in ST but after that nothing works.
Extracted package : https://cl.ly/mbit
Error : https://cl.ly/maup
Can you please let me know what I am doing wrong ?
I am on latest mac on latest ST Dev build.

---------------------------
With Regards
Gagan Janjua

**Comment by ihodev** [comment]
This tab style is already available in [DA UI](https://packagecontrol.io/packages/DA%20UI).
