### ISSUE TITLE
Enhancement - Soda Theme like tabs

### ISSUE THREAD

**Issue by gj1118** [ihodev/sublime-boxy#166]
Hi ,
First things first, I am a huge fan of your theme. I have a request though - Can you please provide an adaptive theme where the tabs are like the tabs in Soda theme 
![image](https://cloud.githubusercontent.com/assets/473101/24959715/7769f286-1f61-11e7-8009-3a126c17d0f7.png)

I am a huge fan of this style of Tabs because it saves space. They get out of the way whenever I am taking a look at my code. I know that asking for a feature like this is time-consuming and that your time is precious and hence I am **# willing to pay you for your time and efforts**. 

Please let me know what you think.  

Thanks
Gagan

**Comment by ihodev** [comment]
@gj1118 Hello, Gagan :wink: I have plans to create a new adaptive theme in the near future with better settings management. I think I'll be able to provide some settings for tabs. Can you tell me a little bit more what exactly do you like in the soda styling of the tabs:

- gradient background,
- tab set bottom border,
- shadows?

Regards,
Ihor

**Comment by gj1118** [comment]
Hi Ihor, 
Thanks for asking. The following are the reasons why I like it so much 
1. In soda theme, the tabs don't occupy much space, whereas, in the latest theme, they occupy a ton of space. See snapshot below 
![image](https://cloud.githubusercontent.com/assets/473101/24960912/39eed094-1f65-11e7-9620-4fc9796880a6.png)
2. There is small empty space after the tab which differentiates between the tab and the code. Please see the snapshot below. The small empty space has been highlighted in yellow. This empty space occupies then entire width of the tabset. This makes Current tab identification much easier as well as distinguishing where the tab ends and the code starts.
![image](https://cloud.githubusercontent.com/assets/473101/24961050/99eab058-1f65-11e7-8c9a-be55f7494a3f.png)
3.The gradients and the shadows though present are very subtle and emphasize the tab's text.
4.The background color of the tab is very light and the color is dark so reading the contents of the tab is very easy on almost all monitors with almost any kind of settings. 
5. there is a clear demarcation between the current highlighted tab and the tabs that are not highlighted.

With the latest UI changes, I think Soda theme is broken. The text doesn't render nicely anymore. And since I am paid to write code all day long, and since I look at the code more often than my wife, it would be nice that my editor is really nice, which is why I am willing to pay you in order to get this done. 

Please let me know what you think. 

Thanks,
Gagan

**Comment by ihodev** [comment]
@gj1118 Thanks for your very clean and exact explanation! I'll be back when I'll have some news for you :wink:

**Comment by gj1118** [comment]
I will be eagerly waiting ... :)

**Comment by gj1118** [comment]
@ihodev I just updated my request.. Sorry for getting so greedy..

**Comment by gj1118** [comment]
@ihodev I know you are super busy, but can you please let me know if you got started on this?

**Comment by ihodev** [comment]
@gj1118 Yes, I'm working on it. I hope I'll finish beta at the end of July.

**Comment by gj1118** [comment]
You are awesome sir, thank you sooo much !!!


---------------------------
With Regards
Gagan Janjua

On Sat, Jun 10, 2017 at 10:43 AM, Ihor Oleksandrov <notifications@github.com

**Comment by ihodev** [comment]
@gj1118 Hello! I'm actively working on the new theme and have some good and bad news for you.

Good:
- Soda like and classic tabs will be implemented.
- Tabset line also will be available.
- Background, foreground & border colors will be highly customizable.
- Also you'll be able to customize font sizes, padding, tab height & etc.

Bad:
- There won't be complex inner shadows & gradients, so the theme will be flat. Skeuomorphic themes require a lot of complex textures those are not customizable at all, so better to create renewed Soda only stuff. However I don't have enough time for that :(
