### ISSUE TITLE
how to set the tab width?

### ISSUE THREAD

**Issue by swinL** [ihodev/sublime-boxy#168]
First of all, thank you very much for your work！

I'm very like the theme, but i hava a problem , that's how can i set the tab width? 

look at the img
![how to set tab witdh](https://cloud.githubusercontent.com/assets/27482687/25038143/ae2c28be-212f-11e7-9e08-8430b86d3f70.jpg)

please tell me，thanks！

**Comment by ihodev** [comment]
@swinL Currently it's only possible via manual customization. See:

- https://github.com/ihodev/sublime-boxy/wiki/Settings#advanced
- https://www.sublimetext.com/docs/3/themes.html

for details. However I've started work on the new theme which will allow you to do this, so keep in touch, I'll be back when I'll have some news :wink:

**Comment by swinL** [comment]
@ihodev  thanks, Looking forward to your new work

**Comment by ihodev** [comment]
[DA UI](https://packagecontrol.io/packages/DA%20UI) beta is already released. 

So now you can change `width` and `min-width` of the tabs:

1. [Try it](https://packagecontrol.io/packages/DA%20UI).
2. Choose `Command Palette › DA UI: Theme Settings`.
3. Find "Tab" settings section.
4. Change everything you need.
