### ISSUE TITLE
Support for custom title bar color on OS X

### ISSUE THREAD

**Issue by danieldiekmeier** [ihodev/sublime-boxy#169]
Sublime Text supports custom title bar colors since `Build 3127`:

> Support for custom color window title bars on OS X 10.10+

See here: http://www.sublimetext.com/3dev

And here is some documentation: https://www.sublimetext.com/docs/3/themes.html#elements-windows

I think this is a rather small change. Can we have this for Boxy? :)

**Comment by ihodev** [comment]
That's in my TODO :wink: I'll be back when I'll have some free time.

**Comment by Superpencil** [comment]
@ihodev would be reallllly hotttt 💦

**Comment by ihodev** [comment]
@danieldiekmeier @Superpencil I'll add title bar styles when I finish my work on the new theme. There will be the last release, which will contain @r-stein PRs, the title bar styling, some fixes to support next version of the [A File Icon](https://github.com/ihodev/a-file-icon) and the announcement of new theme.

I've decided to deprecate Boxy in favor of the new theme, which will be adaptive, more customizable and extendable.

**Comment by Superpencil** [comment]
@ihodev Looking forward to it, hope you get to beta soon so we can all complain your ears off about everything wrong before release ;)

**Comment by Superpencil** [comment]
@ihodev public beta time with 3.0 out?

**Comment by kinglozzer** [comment]
If anyone stumbles upon this (like I did) and is impatient (like I am), you can achieve this by creating a file named `<package-dir>/User/<theme name>.sublime-theme`. For example, I’m on Mac using Boxy Ocean, so mine looks like this:

`~/Library/Application Support/Sublime Text 3/Packages/User/Boxy Ocean.sublime-theme`:
```json
[
  {
    "class": "title_bar",
    "bg": [34, 50, 58],
    "fg": [255, 255, 255]
  }
]
```

**Comment by ihodev** [comment]
Yeah, I know :wink: I wasn't expecting to see a new stable ST so early. I hope you'll see the first beta of the new theme on Monday / Tuesday. Then I'll start working on the new release of `A File Icon`. Please wait a little :smile:

**Comment by Superpencil** [comment]
@ihodev hey the sublime team has a core policy of full opaqueness. show them some respect! 🤓

**Comment by ihodev** [comment]
Ok, some users doesn't like the colored title bars, because of 

> Colored title bars disable macOS Sierra tabs.

I've decided to abandon this issue. [My new theme](https://packagecontrol.io/packages/DA%20UI) has settings to disable/enable custom title bars. I hope you'll like it.
