### ISSUE TITLE
Customization (font-size) for output panel?

### ISSUE THREAD

**Issue by Asitis** [ihodev/sublime-boxy#171]
As the others wrote; Boxy is the best theme I've found so far, and loving it's configurability. But the more I can edit, the more the things I can't edit stand out.

As far as I see, there are no options available for customizing the output panel (like seen in SFTP)? The huge font-size there annoys me more then it should. I've tried all the size options, but none seem to affect this box:

![screenshot from 2017-04-26 11-31-21](https://cloud.githubusercontent.com/assets/9464641/25427783/eb50f682-2a73-11e7-8f88-8d7de40de40e.png)

**Comment by ihodev** [comment]
Currently I'm working on the new theme. It will allow you to do such customization easily. I'll be back when I'll have some news for you :wink:

**Comment by ihodev** [comment]
@Asitis Hello! [DA UI](https://packagecontrol.io/packages/DA%20UI) Beta is available and you can change that font size via `DA UI: Widget Settings`. If you miss some `Boxy` features feel free to file your suggestions [here](https://github.com/ihodev/sublime-da-ui).
