### ISSUE TITLE
Include zenburn as a theme & colormap?

### ISSUE THREAD

**Issue by AllanLRH** [ihodev/sublime-boxy#175]
Would it be possible to include [Zenburn](http://colinta.com/projects/zenburn_color_scheme.html) in boxy? It includes a theme and a color scheme, and IMHO it's a really nice color scheme!

**CSS**
![CSS](https://camo.githubusercontent.com/404428b84417b9b10522677bfe804f420ac3b0bc/687474703a2f2f636f6c696e74612e636f6d2f7374617469632f696d6167652f7a656e6275726e2f68746d6c2e706e67)

**HTML**
![HTML](https://camo.githubusercontent.com/1e15a1ec399cc33e21e3eb930c2775afd72a5642/687474703a2f2f636f6c696e74612e636f6d2f7374617469632f696d6167652f7a656e6275726e2f6373732e706e67)

**Python**
![Python](https://camo.githubusercontent.com/72bb280be05aab789404c9aadda6c8e2ca0579ab/687474703a2f2f636f6c696e74612e636f6d2f7374617469632f696d6167652f7a656e6275726e2f707974686f6e2e706e67)

**Ruby**
![Ruby](https://camo.githubusercontent.com/68ed4d8808aea87e3c4082705dea6106cf0ed462/687474703a2f2f636f6c696e74612e636f6d2f7374617469632f696d6167652f7a656e6275726e2f727562792e706e67)

**Comment by ihodev** [comment]
Hello @AllanLRH,

Please forgive my long silence. This theme will be deprecated in the near future. Now, you can try [my new theme](https://packagecontrol.io/packages/DA%20UI).

I've added Zenburn color scheme to [DA CS](https://github.com/ihodev/sublime-da-cs) package. Currently you can install it manually or just [wait till it will be](https://github.com/wbond/package_control_channel/pull/6630) on Package Control.
