### ISSUE TITLE
Text in tabs can get truncated vertically

### ISSUE THREAD

**Issue by ACinnamonUserInUK** [ihodev/sublime-boxy#177]
**Screenshot** (see the word 'original').

![image](https://cloud.githubusercontent.com/assets/9998846/26131952/8ba1fe56-3a8c-11e7-8ee4-04797ebed71b.png)

**My environment**

Boxy Theme: 5.2.0
Sublime Text: 3126
If you can give me an easy way to dump the more specific, relevant theme settings, then I'll do it.

OS: Linux Mint 18.1 Serena x86_64 
Kernel: 4.10.0-20-generic 
Shell: /bin/bash 
 Resolution: 1280x800 
DE: Cinnamon 3.2.7 
WM: Mutter (Muffin) 
WM Theme: Cinnamon (SimpleX-Grayscale_NJ) 
Theme: Mint-Y [GTK2/3] 
 Icons: Paper [GTK2/3] 
Font: Noto Sans UI 11 [GTK2/3]

**Comment by ihodev** [comment]
@ACinnamonUserInUK Hello! That's Sublime Text issue. It was fixed in 3127+.

**Comment by ACinnamonUserInUK** [comment]
Thanks. I discover that that build is available from here: [www.sublimetext.com/3dev](url) and _not_ from www.sublimetext.com/3.
