### ISSUE TITLE
Problems with the JavaScript syntax highlighter

### ISSUE THREAD

**Issue by andreamoro** [ihodev/sublime-boxy#178]
I'm not entirely sure this can be file as a bug, nor this depends from the theme, but it's better to start a conversation also here in order to find an answer.

I've opened this [thread](https://stackoverflow.com/questions/44176616/sublimetext-3-better-support-for-jquery-syntax-highilight) on StackOverflow with details.

Thanks.

**Comment by ihodev** [comment]
Hello, @andreamoro. It seems that you've installed some custom js syntax or try to clean sublime cache and restart it. Everything is ok from my side:

![image](https://cloud.githubusercontent.com/assets/9801624/26447866/324c4168-4153-11e7-821f-09d8bdae4dfd.png)
