### ISSUE TITLE
Not all file type icons showing up in sidebar on Linux

### ISSUE THREAD

**Issue by witsec** [ihodev/sublime-boxy#181]
Just upgraded to version 5.2.0 on Linux and noticed not all file type icons are displayed or loaded:

![image](http://i.imgur.com/qHo8IyO.png)

The icons work fine up until version 4.0.0. From version 5.0.0 and up, I get the behaviour above.
They work OK on Windows though.

Any ideas?

**Comment by ihodev** [comment]
@witsec Please, see [this](https://github.com/ihodev/sublime-boxy#icons). In short, just install [A File Icon](https://packagecontrol.io/packages/A%20File%20Icon).

**Comment by witsec** [comment]
Ah, right. Works now, thanks! :)
