### ISSUE TITLE
Adding Support for OperatorMono Font

### ISSUE THREAD

**Issue by swashata** [ihodev/sublime-boxy#183]
Hi,

First of all excellent theme and color schemes for Sublime Text. I have been using it for more than a year and very happy with it.

Recently I was playing with Operator Mono font and I had to add the following snippet to the color scheme to make it work as per the attached screenshot.

```xml
		<!-- Operator Tweaks -->
		<dict>
			<key>name</key>
			<string>Italic HTML attribute names</string>
			<key>scope</key>
			<string>entity.other.attribute-name.html,punctuation.section.embedded.begin.php,punctuation.section.embedded.end.php,entity.other.attribute-name.class.html,entity.other.attribute-name.id.html</string>
			<key>settings</key>
			<dict>
				<key>fontStyle</key>
				<string>italic</string>
			</dict>
		</dict>
```

![2017-07-21_21-58-33](https://user-images.githubusercontent.com/1623381/28473184-2d30a9c2-6e61-11e7-97dd-13110a97e4bf.jpg)

I was hoping you can perhaps integrate it in a better way and add italics version of your color scheme.

**Comment by ihodev** [comment]
Hello @swashata,

Please forgive my long silence. This theme will be deprecated in the near future. Now, you can try [my new theme](https://packagecontrol.io/packages/DA%20UI). Almost all your italic suggestions are already there.

All the Boxy color schemes will be available soon in the [other package](https://github.com/ihodev/sublime-da-cs).

**Comment by swashata** [comment]
The new theme is just "AWESOME". I am going to be one of the first to purchase.

One request, if you could have the tomorrow color scheme. I am just so used to it.

**Comment by ihodev** [comment]
> One request, if you could have the tomorrow color scheme. I am just so used to it.

Ok, [DA CS](https://github.com/ihodev/sublime-da-cs) is finally ready. Currently you can install it manually, however it will be available [soon](https://github.com/wbond/package_control_channel/pull/6630) on Package Control.

Boxy Tomorrow was significantly inspired by [Tomorrow Dark](https://github.com/ihodev/sublime-da-cs#tomorrow-dark), so now you can use it :wink:
