### ISSUE TITLE
Why my sidebar catalog color is not bright it too

### ISSUE THREAD

**Issue by ArmorHerO** [ihodev/sublime-boxy#184]
My sidebar of the directory orange is too dark, is where I set up wrong? Where should this change?I have set the “ theme_sidebar_icon_saturation_xh ”： true.
I'm sorry for my English。
![image](https://user-images.githubusercontent.com/18901031/29495043-5b8030e6-85e9-11e7-9ce8-267c893e315c.png)

**Comment by ihodev** [comment]
@ArmorHerO Hello, try to restart and please provide your full settings list.

**Comment by specialGirl** [comment]
{
	"auto_complete_triggers":
	[
		{
			"characters": "1234567890abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ.<",
			"selector": "text.html"
		},
		{
			"characters": "1234567890abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ.<",
			"selector": "text.plain"
		}
	],
	"color_scheme": "Packages/Boxy Theme/schemes/Boxy Monokai.tmTheme",
	"font_size": 13,
	"ignored_packages":
	[
		"Vintage"
	],
	"line_padding_bottom": 0,
	"line_padding_top": 4,
	"theme": "Boxy Monokai.sublime-theme",
	"theme_accent_tangerine": true,
	"theme_autocomplete_item_selected_colored": true,
	"theme_bar_margin_top_sm": true,
	"theme_dropdown_atomized": true,
	"theme_find_panel_close_hidden": true,
	"theme_icon_button_highlighted": true,
	"theme_quick_panel_item_selected_colored": true,
	"theme_quick_panel_size_md": true,
	"theme_scrollbar_colored": true,
	"theme_scrollbar_line": true,
	"theme_sidebar_border": true,
	"theme_sidebar_disclosure": true,
	"theme_sidebar_font_md": true,
	"theme_sidebar_font_sm": true,
	"theme_sidebar_icon_saturation_xh": true,
	"theme_sidebar_indent_top_level_disabled": true,
	"theme_sidebar_size_xs": true,
	"theme_statusbar_size_md": true,
	"theme_tab_close_always_visible": true,
	"theme_tab_font_xl": true,
	"theme_tab_selected_overlined": true,
	"theme_tab_size_md": true
}

this is my setting,i have restart and now it is not ok

**Comment by ihodev** [comment]
Did your customized it manually? Your config works as expected on my Windows machine.

**Comment by ArmorHerO** [comment]
I do not have manual customization,i am mac,i try to uninstall and reload the results are still the same，i am sorry ,i went to my wife's account before ,the specialGirl

**Comment by ihodev** [comment]
I think that something changes opacity level of your `folder icons`. Folder icons should be affected by `A File Icon`.

**Comment by ihodev** [comment]
Try to remove all Boxy-related settings and see if folders are bright. Also maybe you need to clear ST Cache folder.

**Comment by ArmorHerO** [comment]
how to  clear ST Cache folder? i can not find it

**Comment by ihodev** [comment]
`~/Library/Application Support/Sublime Text 3/Cache`

**Comment by ArmorHerO** [comment]
i remove the Cache floder and I uninstalled and re-installed boxy, the problem still exists，Maybe one of my other plugins has had an impact on it

**Comment by ihodev** [comment]
I think yes, could your provide the list of installed packages?

Open `Preferences -> Package Settings -> Package Control -> Settings - User` and copy `installed_packages`.

**Comment by ArmorHerO** [comment]
this is 

<img width="311" alt="2017-08-29 8 13 56" src="https://user-images.githubusercontent.com/18901031/29820349-c50e55e2-8cf6-11e7-8b5c-a522ca5dc00d.png">

**Comment by ihodev** [comment]
Try to disable `Side Bar`. However, really don't know what can affect theme in your case.

**Comment by ArmorHerO** [comment]
That is what I installed today plug-in, before loading the plug-in this problem already exists，I'm trying to try something else, and what will I do with the feedback，thank you very much。

**Comment by ArmorHerO** [comment]
@ihodev I found the problem, the cause of SyncedSidebarBg plugin, I uninstalled this plugin, everything is normal
