### ISSUE TITLE
How to change the sidebar file icons to Seti UI?

### ISSUE THREAD

**Issue by Thoufeeq** [ihodev/sublime-boxy#186]
I could see the current file icons used in Boxy theme is **zzz A File Icon zzz**. How can I change that to **Seti Ui**, which I think would be a great combination for your ocean version of Boxy?

![screenshot-3](https://user-images.githubusercontent.com/1624532/29758907-f2e3cf56-8bd4-11e7-8a0a-ae686d7fab79.png)

**Comment by ihodev** [comment]
You can try next steps:
1. Create `Packages/User/SetiAndBoxy` folder
2. Create `Boxy Ocean.sublime-theme` with next contents:
```js
[
  // Boxy Ocean Patch
  // ==========================================================================

  // Sidebar File Icons
  // --------------------------------------------------------------------------

  // Default

  {
    "class": "icon_file_type",
    "layer0.tint": [255, 255, 255],
    "layer0.opacity": 0.75,
    "content_margin": [8, 8]
  },

  // Hovered

  {
    "class": "icon_file_type",
    "parents": [{"class": "tree_row", "attributes": ["hover"]}],
    "layer0.opacity": 0.5
  },

  // Selected

  {
    "class": "icon_file_type",
    "parents": [{"class": "tree_row", "attributes": ["selected"]}],
    "layer0.opacity": 1.0
  }
]
```
3. Copy `Seti` icons in that folder.
