### ISSUE TITLE
How to change the popup_panel font face

### ISSUE THREAD

**Issue by easyfrog** [ihodev/sublime-boxy#187]
Hi . I use `Boxy Theme Addon - Font Face` to change the font.  But I don't know how to change popup control's font face.
![ae82e14f-3446-49bb-8423-623286dc56fa](https://user-images.githubusercontent.com/10724325/29801263-5e97242e-8ca1-11e7-9104-d3491daa0b1c.png)

**Comment by ihodev** [comment]
Hi, @easyfrog. You can change popup font face starting ST 3127+, please wait next stable ST version.

**Comment by Thoufeeq** [comment]
@easyfrog Your tab separator is just fine. I have this faded lines:

![screen shot 2017-08-30 at 8 46 15 am](https://user-images.githubusercontent.com/1624532/29853867-f6f16860-8d5f-11e7-8268-64ec6ed7542d.png)

Also, what font for tabs? 
Thanks

**Comment by easyfrog** [comment]
Hi @Thoufeeq I don't know why your tab separator is a faded lines. Maybe reinstall Boxy theme ? I don't know.

And if you want change Boxy theme's font. you should install `Boxy Theme Addon - Font Face` in PackageControl. 

I use the default font face named `Sans-Serif`.
￼
![bb06359c-97d7-4ec0-b98b-886e5a00107d](https://user-images.githubusercontent.com/10724325/29861880-681f4218-8d9d-11e7-8b9b-20184a8381de.png)

And use `PackageResourceViewer` to edit this font theme will be more easier.

![89045466-c608-494c-85d4-8dcd84a84553](https://user-images.githubusercontent.com/10724325/29862083-165659a2-8d9e-11e7-8b4c-b716dc6086cf.png)

**Comment by ihodev** [comment]
@Thoufeeq Please post your config. I think you just need to remove one setting :wink:

**Comment by easyfrog** [comment]
@ihodev 

> Hi, @easyfrog. You can change popup font face starting ST 3127+, please wait next stable ST version.

I check my ST version is 3142 .But also can not change the popup control font face.

**Comment by ihodev** [comment]
That's because `Boxy Theme Addon - Font Face` doesn't support that, you can add next code manually

```json
  {
    "class": "quick_panel_label",
    "font.face" "Sans-Serif"
  },
  {
    "class": "quick_panel_path_label",
    "font.face" "Sans-Serif"
  },
```

P.S. I'm actively working on the new theme, which I hope will be ready before next ST stable release. You'll be able to change such things easily with it.

**Comment by Thoufeeq** [comment]
Here's my config:

```
{
	"always_show_minimap_viewport": true,
	"bold_folder_labels": true,
	"caret_extra_bottom": 1,
	"caret_extra_top": 1,
	"caret_extra_width": 1,
	"caret_style": "blink",
	"color_scheme": "Packages/Boxy Theme/schemes/Boxy Ocean.tmTheme",
	"fade_fold_buttons": false,
	"folder_exclude_patterns":
	[
		".svn",
		".git",
		".hg",
		"CVS",
		"node_modules",
		"build"
	],
	"font_face": "Source Code Pro",
	"font_options":
	[
		"no_round"
	],
	"font_size": 15,
	"ignored_packages":
	[
		"Vintage"
	],
	"line_padding_bottom": 2,
	"line_padding_top": 2,
	"overlay_scroll_bars": "enabled",
	"scroll_past_end": true,
	"show_encoding": true,
	"show_line_endings": true,
	"tab_size": 2,
	"theme": "Boxy Ocean.sublime-theme",
	"theme_bar": true,
	"theme_bar_logo_atomized": true,
	"theme_bar_shadow_hidden": true,
	"theme_dirty_colored_always": true,
	"theme_dirty_materialized": true,
	"theme_dropdown_materialized": true,
	"theme_icons_materialized": true,
	"theme_scrollbar_rounded": true,
	"theme_sidebar_folder_materialized": true,
	"theme_sidebar_indent_xl": true,
	"theme_tab_rounded": true,
	"theme_tab_selected_transparent": true,
	"theme_tab_selected_underlined": true,
	"theme_tab_separator": true,
	"theme_tab_size_xxl": true,
	"theme_unified": true
}

```

**Comment by ihodev** [comment]
@Thoufeeq Remove or set to `false`:

```json
  "theme_tab_rounded": false,
```

**Comment by Thoufeeq** [comment]
Tried removing, didn't work. Tried setting the value to false as well, didn't work.
