### ISSUE TITLE
Missing WEBP file icon

### ISSUE THREAD

**Issue by djmtype** [ihodev/sublime-boxy#193]
A webp file icon appears to be missing.
A webp file icon should appear next to .webp files.

I'm not sure if I should post the issue here or with [A File Icon](https://github.com/ihodev/a-file-icon), but I've tried reverting to a fresh state and get the same results – missing .webp icon.

Running Sublime v3, 3143. MacOS High Sierra.

**Comment by ihodev** [comment]
@djmtype Hello!

Thanks! Yes, it's missing now. I've created an issue for that [here](https://github.com/ihodev/a-file-icon/issues/143). It will be added with the next version of `A File Icon`.

> I'm not sure if I should post the issue here or with A File Icon, but I've tried reverting to a fresh state and get the same results – missing .webp icon.

Next time please file your icon-related issues at [A File Icon](https://github.com/ihodev/a-file-icon/issues) :wink: 

P.S. Note, this theme will be deprecated later this year. Consider giving a try to [my new theme](https://packagecontrol.io/packages/DA%20UI).
