### ISSUE TITLE
Changing find panel font size doesn't change input's font size

### ISSUE THREAD

**Issue by fnando** [ihodev/sublime-boxy#194]
#### Expected Behavior

Font size of inputs to be large(r).

#### Current Behavior

The UI font size changes, but the input keeps small(r).

#### Steps to Reproduce (for bugs)

1. Boxy Theme: Configuration > Find Panels > Find Panel Font > click on theme_find_panel_font_xl

#### Your Environment

- Boxy Theme: 5.2.0
- Sublime Text: 3147
- Platform: osx
- Package Control: True
- Dependencies:
    * mdpopups: 2.1.1
    * markdown: 2.6.9
    * pygments: 2.1a0
    * jinja2: 2.8

**Comment by ihodev** [comment]
Hello @fnando ! You can try this addon: https://github.com/ihodev/sublime-boxy-addon-widget-font-size

However, see the [warning](https://github.com/ihodev/sublime-boxy/blob/dev/README.md). Boxy will be deprecated in the near future, so I recommend you give [DA UI](https://packagecontrol.io/packages/DA%20UI) a try it allows you to do a lot more than Boxy. Also there is [DA CS](https://github.com/ihodev/sublime-da-cs) package which contains dozens of color schemes, including all Boxy ones. It's currently not on Package Control, but it will be available soon.

**Comment by fnando** [comment]
Thanks! I just migrated to DA UI. <3
