### ISSUE TITLE
there is a way to use the palenight color theme?

### ISSUE THREAD

**Issue by betorobson** [ihodev/sublime-boxy#195]
I would like to use palenight color theme like Material Theme does. There is a way to do it?

https://github.com/JonathanSpeek/palenight-iterm2

**Comment by ihodev** [comment]
Hello! Boxy theme will be deprecated in the near future, try

[DA UI](https://packagecontrol.io/packages/DA%20UI) – my new theme, its engine allows you to do a lot more than Boxy settings abuse.
[DA CS](https://packagecontrol.io/packages/DA%20CS) – the pack of popular color schemes, it includes `Palenight` too.

I hope, you'll like it :wink:

**Comment by betorobson** [comment]
thank you !!! you rock!!!
