### ISSUE TITLE
How to show the sidebar file icon,not </> ,such as *.py？

### ISSUE THREAD

**Issue by xianggithubli** [ihodev/sublime-boxy#196]
Mono file icons is installed.
#### Your Environment
Boxy Theme: 5.2.0
- Sublime Text: 3143
- Platform: windows
- Package Control: True
- Dependencies:
    * mdpopups: 3.0.3
    * markdown: 2.6.9
    * pygments: 2.1a0
    * jinja2: 2.8

#### Steps to Reproduce (for bugs)

1.
2.
3.

**Comment by ihodev** [comment]
Install `A File Icon` package :wink:

**Comment by xianggithubli** [comment]
Tks,It works.
